spring.application.name=clothing-shop-pos

spring.profiles.include=secret

# Database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/clothing_shop_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

# JWT
sapo.jwt.access-token-validity-in-seconds=86400
sapo.jwt.refresh-token-validity-in-seconds=604800





# -----------------------
# Pagable
# -----------------------
# Default page size
spring.data.web.pageable.default-page-size=5
# start page from 1 (instead of 0)
spring.data.web.pageable.one-indexed-parameters=true
# parameter name
spring.data.web.pageable.page-parameter=page
spring.data.web.pageable.size-parameter=size
spring.data.web.sort.sort-parameter=sort

# Jackson
spring.jackson.deserialization.fail-on-unknown-properties=false


# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manhwakunchi@gmail.com
spring.mail.password=wmezdfmiesmijaad

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# AI Gemini API (Mapping from Environment Variables)
ai.gemini.api-key=${AI_GEMINI_API_KEY:}
ai.gemini.api-url=${AI_GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent}


# Prometheus / Actuator
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=clothing-shop-be
