spring.application.name=clothing-shop-pos

# Load secret properties (gitignore file này)
spring.profiles.include=secret

# Database
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://localhost:3306/clothing_shop_db
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

# JWT
hoangmelinh.jwt.access-token-validity-in-seconds=86400
hoangmelinh.jwt.refresh-token-validity-in-seconds=604800



# Pagination (1-indexed)
spring.data.web.pageable.one-indexed-parameters=true
